name: Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '0 0 * * 0' # Weekly on Sunday

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
    
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y jq
        npm install
    
    - name: Run tests
      run: npm test
    
    - name: Check if ccusage still works
      run: |
        # Test that ccusage can be installed and run
        output=$(npx ccusage@15.5.2 blocks --json 2>&1 || echo "No data")
        echo "ccusage output: $output"
        
        # Check if it's valid JSON (when data exists) or expected error
        if [[ "$output" == *"{"* ]] || [[ "$output" == *"No data"* ]] || [[ "$output" == *"No project directories found"* ]]; then
          echo "✓ ccusage is accessible"
        else
          echo "✗ Unexpected ccusage output"
          exit 1
        fi