name: Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '0 0 * * 0' # Weekly on Sunday

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
    
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y jq
        npm install
    
    - name: Run tests
      run: npm test
    
    - name: Check if ccusage still works
      run: |
        # Test that ccusage can be installed and has expected commands
        npx ccusage@15.5.2 --help 2>&1 | grep -q "blocks" || {
          echo "ccusage doesn't have expected 'blocks' command"
          exit 1
        }
        echo "✓ ccusage is accessible and has blocks command"